const data = {
  location: {
    name: "London",
    region: "City of London, Greater London",
    country: "United Kingdom",
    lat: 51.52,
    lon: -0.11,
    tz_id: "Europe/London",
    localtime_epoch: 1706647469,
    localtime: "2024-01-30 20:44",
  },
  current: {
    last_updated_epoch: 1706646600,
    last_updated: "2024-01-30 20:30",
    temp_c: 7,
    temp_f: 44.6,
    is_day: 0,
    condition: {
      text: "Partly cloudy",
      icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
      code: 1003,
    },
    wind_mph: 3.8,
    wind_kph: 6.1,
    wind_degree: 310,
    wind_dir: "NW",
    pressure_mb: 1034,
    pressure_in: 30.53,
    precip_mm: 0,
    precip_in: 0,
    humidity: 81,
    cloud: 75,
    feelslike_c: 6.2,
    feelslike_f: 43.2,
    vis_km: 10,
    vis_miles: 6,
    uv: 1,
    gust_mph: 5.1,
    gust_kph: 8.1,
  },
  forecast: {
    forecastday: [
      {
        date: "2024-01-30",
        date_epoch: 1706572800,
        day: {
          maxtemp_c: 8.8,
          maxtemp_f: 47.9,
          mintemp_c: 5,
          mintemp_f: 41,
          avgtemp_c: 8.2,
          avgtemp_f: 46.7,
          maxwind_mph: 16.6,
          maxwind_kph: 26.6,
          totalprecip_mm: 0.33,
          totalprecip_in: 0.01,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 79,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 86,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain nearby",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 1,
        },
        astro: {
          sunrise: "07:43 AM",
          sunset: "04:45 PM",
          moonrise: "09:59 PM",
          moonset: "09:34 AM",
          moon_phase: "Waning Gibbous",
          moon_illumination: 84,
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1706572800,
            time: "2024-01-30 00:00",
            temp_c: 11,
            temp_f: 51.8,
            is_day: 0,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 13.2,
            wind_kph: 21.2,
            wind_degree: 205,
            wind_dir: "SSW",
            pressure_mb: 1021,
            pressure_in: 30.14,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 88,
            cloud: 100,
            feelslike_c: 8.5,
            feelslike_f: 47.4,
            windchill_c: 8.5,
            windchill_f: 47.4,
            heatindex_c: 11,
            heatindex_f: 51.8,
            dewpoint_c: 9.1,
            dewpoint_f: 48.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 20.5,
            gust_kph: 33,
            uv: 1,
          },
          {
            time_epoch: 1706576400,
            time: "2024-01-30 01:00",
            temp_c: 11.2,
            temp_f: 52.2,
            is_day: 0,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 14.8,
            wind_kph: 23.8,
            wind_degree: 208,
            wind_dir: "SSW",
            pressure_mb: 1020,
            pressure_in: 30.13,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 84,
            cloud: 100,
            feelslike_c: 8.6,
            feelslike_f: 47.5,
            windchill_c: 8.6,
            windchill_f: 47.5,
            heatindex_c: 11.2,
            heatindex_f: 52.2,
            dewpoint_c: 8.7,
            dewpoint_f: 47.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 22.2,
            gust_kph: 35.7,
            uv: 1,
          },
          {
            time_epoch: 1706580000,
            time: "2024-01-30 02:00",
            temp_c: 11.1,
            temp_f: 51.9,
            is_day: 0,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 16.6,
            wind_kph: 26.6,
            wind_degree: 215,
            wind_dir: "SW",
            pressure_mb: 1020,
            pressure_in: 30.12,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 76,
            cloud: 100,
            feelslike_c: 8.2,
            feelslike_f: 46.8,
            windchill_c: 8.2,
            windchill_f: 46.8,
            heatindex_c: 11.1,
            heatindex_f: 51.9,
            dewpoint_c: 7,
            dewpoint_f: 44.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 23.9,
            gust_kph: 38.4,
            uv: 1,
          },
          {
            time_epoch: 1706583600,
            time: "2024-01-30 03:00",
            temp_c: 11,
            temp_f: 51.7,
            is_day: 0,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 13,
            wind_kph: 20.9,
            wind_degree: 213,
            wind_dir: "SSW",
            pressure_mb: 1020,
            pressure_in: 30.13,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 77,
            cloud: 100,
            feelslike_c: 8.5,
            feelslike_f: 47.3,
            windchill_c: 8.5,
            windchill_f: 47.3,
            heatindex_c: 11,
            heatindex_f: 51.7,
            dewpoint_c: 7,
            dewpoint_f: 44.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 19.5,
            gust_kph: 31.4,
            uv: 1,
          },
          {
            time_epoch: 1706587200,
            time: "2024-01-30 04:00",
            temp_c: 10.5,
            temp_f: 50.9,
            is_day: 0,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 13,
            wind_kph: 20.9,
            wind_degree: 214,
            wind_dir: "SW",
            pressure_mb: 1020,
            pressure_in: 30.13,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 82,
            cloud: 97,
            feelslike_c: 7.9,
            feelslike_f: 46.2,
            windchill_c: 7.9,
            windchill_f: 46.2,
            heatindex_c: 10.5,
            heatindex_f: 50.9,
            dewpoint_c: 7.5,
            dewpoint_f: 45.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 18.8,
            gust_kph: 30.2,
            uv: 1,
          },
          {
            time_epoch: 1706590800,
            time: "2024-01-30 05:00",
            temp_c: 9.6,
            temp_f: 49.2,
            is_day: 0,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 14.1,
            wind_kph: 22.7,
            wind_degree: 235,
            wind_dir: "SW",
            pressure_mb: 1021,
            pressure_in: 30.15,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 82,
            cloud: 100,
            feelslike_c: 6.6,
            feelslike_f: 43.9,
            windchill_c: 6.6,
            windchill_f: 43.9,
            heatindex_c: 9.6,
            heatindex_f: 49.2,
            dewpoint_c: 6.7,
            dewpoint_f: 44.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 19.1,
            gust_kph: 30.7,
            uv: 1,
          },
          {
            time_epoch: 1706594400,
            time: "2024-01-30 06:00",
            temp_c: 8.8,
            temp_f: 47.9,
            is_day: 0,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 13.9,
            wind_kph: 22.3,
            wind_degree: 244,
            wind_dir: "WSW",
            pressure_mb: 1022,
            pressure_in: 30.18,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 80,
            cloud: 100,
            feelslike_c: 5.7,
            feelslike_f: 42.2,
            windchill_c: 5.7,
            windchill_f: 42.2,
            heatindex_c: 8.8,
            heatindex_f: 47.9,
            dewpoint_c: 5.5,
            dewpoint_f: 42,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 19,
            gust_kph: 30.6,
            uv: 1,
          },
          {
            time_epoch: 1706598000,
            time: "2024-01-30 07:00",
            temp_c: 8.4,
            temp_f: 47.1,
            is_day: 0,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 13,
            wind_kph: 20.9,
            wind_degree: 255,
            wind_dir: "WSW",
            pressure_mb: 1023,
            pressure_in: 30.22,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 78,
            cloud: 100,
            feelslike_c: 5.3,
            feelslike_f: 41.5,
            windchill_c: 5.3,
            windchill_f: 41.5,
            heatindex_c: 8.4,
            heatindex_f: 47.1,
            dewpoint_c: 4.8,
            dewpoint_f: 40.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 17.3,
            gust_kph: 27.9,
            uv: 1,
          },
          {
            time_epoch: 1706601600,
            time: "2024-01-30 08:00",
            temp_c: 8.2,
            temp_f: 46.7,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 11.2,
            wind_kph: 18,
            wind_degree: 262,
            wind_dir: "W",
            pressure_mb: 1025,
            pressure_in: 30.25,
            precip_mm: 0.03,
            precip_in: 0,
            snow_cm: 0,
            humidity: 77,
            cloud: 96,
            feelslike_c: 5.3,
            feelslike_f: 41.5,
            windchill_c: 5.3,
            windchill_f: 41.5,
            heatindex_c: 8.2,
            heatindex_f: 46.7,
            dewpoint_c: 4.4,
            dewpoint_f: 39.9,
            will_it_rain: 1,
            chance_of_rain: 71,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.1,
            gust_kph: 24.3,
            uv: 2,
          },
          {
            time_epoch: 1706605200,
            time: "2024-01-30 09:00",
            temp_c: 8,
            temp_f: 46.4,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 269,
            wind_dir: "W",
            pressure_mb: 1026,
            pressure_in: 30.29,
            precip_mm: 0.13,
            precip_in: 0,
            snow_cm: 0,
            humidity: 79,
            cloud: 96,
            feelslike_c: 5.3,
            feelslike_f: 41.6,
            windchill_c: 5.3,
            windchill_f: 41.6,
            heatindex_c: 8,
            heatindex_f: 46.4,
            dewpoint_c: 4.7,
            dewpoint_f: 40.4,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.2,
            gust_kph: 21.2,
            uv: 2,
          },
          {
            time_epoch: 1706608800,
            time: "2024-01-30 10:00",
            temp_c: 7.8,
            temp_f: 46.1,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 281,
            wind_dir: "WNW",
            pressure_mb: 1027,
            pressure_in: 30.32,
            precip_mm: 0.01,
            precip_in: 0,
            snow_cm: 0,
            humidity: 81,
            cloud: 97,
            feelslike_c: 5.4,
            feelslike_f: 41.7,
            windchill_c: 5.4,
            windchill_f: 41.7,
            heatindex_c: 7.8,
            heatindex_f: 46.1,
            dewpoint_c: 4.7,
            dewpoint_f: 40.5,
            will_it_rain: 1,
            chance_of_rain: 75,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.6,
            gust_kph: 18.6,
            uv: 2,
          },
          {
            time_epoch: 1706612400,
            time: "2024-01-30 11:00",
            temp_c: 7.9,
            temp_f: 46.3,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 283,
            wind_dir: "WNW",
            pressure_mb: 1028,
            pressure_in: 30.35,
            precip_mm: 0.01,
            precip_in: 0,
            snow_cm: 0,
            humidity: 79,
            cloud: 100,
            feelslike_c: 5.7,
            feelslike_f: 42.3,
            windchill_c: 5.7,
            windchill_f: 42.3,
            heatindex_c: 7.9,
            heatindex_f: 46.3,
            dewpoint_c: 4.6,
            dewpoint_f: 40.3,
            will_it_rain: 0,
            chance_of_rain: 64,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.4,
            gust_kph: 16.8,
            uv: 2,
          },
          {
            time_epoch: 1706616000,
            time: "2024-01-30 12:00",
            temp_c: 8.2,
            temp_f: 46.8,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 286,
            wind_dir: "WNW",
            pressure_mb: 1028,
            pressure_in: 30.37,
            precip_mm: 0.01,
            precip_in: 0,
            snow_cm: 0,
            humidity: 75,
            cloud: 93,
            feelslike_c: 5.8,
            feelslike_f: 42.4,
            windchill_c: 5.8,
            windchill_f: 42.4,
            heatindex_c: 8.2,
            heatindex_f: 46.8,
            dewpoint_c: 4,
            dewpoint_f: 39.2,
            will_it_rain: 1,
            chance_of_rain: 82,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.9,
            gust_kph: 19.1,
            uv: 2,
          },
          {
            time_epoch: 1706619600,
            time: "2024-01-30 13:00",
            temp_c: 7.8,
            temp_f: 46.1,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 292,
            wind_dir: "WNW",
            pressure_mb: 1029,
            pressure_in: 30.38,
            precip_mm: 0.08,
            precip_in: 0,
            snow_cm: 0,
            humidity: 76,
            cloud: 97,
            feelslike_c: 5.4,
            feelslike_f: 41.6,
            windchill_c: 5.4,
            windchill_f: 41.6,
            heatindex_c: 7.9,
            heatindex_f: 46.1,
            dewpoint_c: 3.9,
            dewpoint_f: 39.1,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.5,
            gust_kph: 18.5,
            uv: 2,
          },
          {
            time_epoch: 1706623200,
            time: "2024-01-30 14:00",
            temp_c: 7.4,
            temp_f: 45.4,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 293,
            wind_dir: "WNW",
            pressure_mb: 1029,
            pressure_in: 30.4,
            precip_mm: 0.04,
            precip_in: 0,
            snow_cm: 0,
            humidity: 80,
            cloud: 100,
            feelslike_c: 5,
            feelslike_f: 41,
            windchill_c: 5,
            windchill_f: 41,
            heatindex_c: 7.4,
            heatindex_f: 45.4,
            dewpoint_c: 4.3,
            dewpoint_f: 39.8,
            will_it_rain: 1,
            chance_of_rain: 75,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.9,
            gust_kph: 17.5,
            uv: 2,
          },
          {
            time_epoch: 1706626800,
            time: "2024-01-30 15:00",
            temp_c: 7.5,
            temp_f: 45.4,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 303,
            wind_dir: "WNW",
            pressure_mb: 1030,
            pressure_in: 30.42,
            precip_mm: 0.02,
            precip_in: 0,
            snow_cm: 0,
            humidity: 80,
            cloud: 96,
            feelslike_c: 5.3,
            feelslike_f: 41.5,
            windchill_c: 5.3,
            windchill_f: 41.5,
            heatindex_c: 7.5,
            heatindex_f: 45.4,
            dewpoint_c: 4.3,
            dewpoint_f: 39.7,
            will_it_rain: 0,
            chance_of_rain: 64,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.8,
            gust_kph: 15.8,
            uv: 2,
          },
          {
            time_epoch: 1706630400,
            time: "2024-01-30 16:00",
            temp_c: 7.6,
            temp_f: 45.6,
            is_day: 1,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 302,
            wind_dir: "WNW",
            pressure_mb: 1031,
            pressure_in: 30.43,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 79,
            cloud: 100,
            feelslike_c: 5.9,
            feelslike_f: 42.7,
            windchill_c: 5.9,
            windchill_f: 42.7,
            heatindex_c: 7.6,
            heatindex_f: 45.6,
            dewpoint_c: 4.2,
            dewpoint_f: 39.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.6,
            gust_kph: 12.2,
            uv: 2,
          },
          {
            time_epoch: 1706634000,
            time: "2024-01-30 17:00",
            temp_c: 7.5,
            temp_f: 45.6,
            is_day: 0,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 308,
            wind_dir: "NW",
            pressure_mb: 1031,
            pressure_in: 30.46,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 77,
            cloud: 88,
            feelslike_c: 6,
            feelslike_f: 42.8,
            windchill_c: 6,
            windchill_f: 42.8,
            heatindex_c: 7.6,
            heatindex_f: 45.6,
            dewpoint_c: 3.7,
            dewpoint_f: 38.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.6,
            gust_kph: 12.2,
            uv: 1,
          },
          {
            time_epoch: 1706637600,
            time: "2024-01-30 18:00",
            temp_c: 7.4,
            temp_f: 45.4,
            is_day: 0,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 307,
            wind_dir: "NW",
            pressure_mb: 1032,
            pressure_in: 30.48,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 73,
            cloud: 100,
            feelslike_c: 5.9,
            feelslike_f: 42.7,
            windchill_c: 5.9,
            windchill_f: 42.7,
            heatindex_c: 7.4,
            heatindex_f: 45.4,
            dewpoint_c: 3,
            dewpoint_f: 37.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.3,
            gust_kph: 11.7,
            uv: 1,
          },
          {
            time_epoch: 1706641200,
            time: "2024-01-30 19:00",
            temp_c: 7,
            temp_f: 44.7,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 326,
            wind_dir: "NNW",
            pressure_mb: 1032,
            pressure_in: 30.49,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 73,
            cloud: 41,
            feelslike_c: 6,
            feelslike_f: 42.9,
            windchill_c: 6,
            windchill_f: 42.9,
            heatindex_c: 7,
            heatindex_f: 44.7,
            dewpoint_c: 2.6,
            dewpoint_f: 36.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.4,
            gust_kph: 8.7,
            uv: 1,
          },
          {
            time_epoch: 1706644800,
            time: "2024-01-30 20:00",
            temp_c: 7,
            temp_f: 44.6,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 310,
            wind_dir: "NW",
            pressure_mb: 1034,
            pressure_in: 30.53,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 81,
            cloud: 75,
            feelslike_c: 5.4,
            feelslike_f: 41.8,
            windchill_c: 5.4,
            windchill_f: 41.8,
            heatindex_c: 6.3,
            heatindex_f: 43.4,
            dewpoint_c: 2.4,
            dewpoint_f: 36.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.1,
            gust_kph: 8.1,
            uv: 1,
          },
          {
            time_epoch: 1706648400,
            time: "2024-01-30 21:00",
            temp_c: 5.8,
            temp_f: 42.4,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 269,
            wind_dir: "W",
            pressure_mb: 1034,
            pressure_in: 30.54,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 77,
            cloud: 16,
            feelslike_c: 4.7,
            feelslike_f: 40.5,
            windchill_c: 4.7,
            windchill_f: 40.5,
            heatindex_c: 5.8,
            heatindex_f: 42.4,
            dewpoint_c: 2.1,
            dewpoint_f: 35.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9,
            uv: 1,
          },
          {
            time_epoch: 1706652000,
            time: "2024-01-30 22:00",
            temp_c: 5.4,
            temp_f: 41.6,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 265,
            wind_dir: "W",
            pressure_mb: 1034,
            pressure_in: 30.55,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 78,
            cloud: 3,
            feelslike_c: 4.2,
            feelslike_f: 39.6,
            windchill_c: 4.2,
            windchill_f: 39.6,
            heatindex_c: 5.4,
            heatindex_f: 41.6,
            dewpoint_c: 1.8,
            dewpoint_f: 35.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.7,
            gust_kph: 9.2,
            uv: 1,
          },
          {
            time_epoch: 1706655600,
            time: "2024-01-30 23:00",
            temp_c: 5,
            temp_f: 41,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 291,
            wind_dir: "WNW",
            pressure_mb: 1035,
            pressure_in: 30.56,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 78,
            cloud: 0,
            feelslike_c: 3.7,
            feelslike_f: 38.6,
            windchill_c: 3.7,
            windchill_f: 38.6,
            heatindex_c: 5,
            heatindex_f: 41,
            dewpoint_c: 1.5,
            dewpoint_f: 34.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.2,
            gust_kph: 10,
            uv: 1,
          },
        ],
      },
      {
        date: "2024-01-31",
        date_epoch: 1706659200,
        day: {
          maxtemp_c: 9.2,
          maxtemp_f: 48.5,
          mintemp_c: 3.6,
          mintemp_f: 38.5,
          avgtemp_c: 6.8,
          avgtemp_f: 44.3,
          maxwind_mph: 14.1,
          maxwind_kph: 22.7,
          totalprecip_mm: 0.01,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 82,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Partly Cloudy ",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          uv: 1,
        },
        astro: {
          sunrise: "07:41 AM",
          sunset: "04:47 PM",
          moonrise: "11:09 PM",
          moonset: "09:43 AM",
          moon_phase: "Waning Gibbous",
          moon_illumination: 77,
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1706659200,
            time: "2024-01-31 00:00",
            temp_c: 4.6,
            temp_f: 40.3,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 297,
            wind_dir: "WNW",
            pressure_mb: 1035,
            pressure_in: 30.56,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 78,
            cloud: 0,
            feelslike_c: 3.8,
            feelslike_f: 38.8,
            windchill_c: 3.8,
            windchill_f: 38.8,
            heatindex_c: 4.6,
            heatindex_f: 40.3,
            dewpoint_c: 1.2,
            dewpoint_f: 34.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.8,
            uv: 1,
          },
          {
            time_epoch: 1706662800,
            time: "2024-01-31 01:00",
            temp_c: 4.4,
            temp_f: 39.9,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 203,
            wind_dir: "SSW",
            pressure_mb: 1034,
            pressure_in: 30.53,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 79,
            cloud: 46,
            feelslike_c: 3.7,
            feelslike_f: 38.6,
            windchill_c: 3.7,
            windchill_f: 38.6,
            heatindex_c: 4.4,
            heatindex_f: 39.9,
            dewpoint_c: 1.1,
            dewpoint_f: 34,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.6,
            gust_kph: 7.4,
            uv: 1,
          },
          {
            time_epoch: 1706666400,
            time: "2024-01-31 02:00",
            temp_c: 4.2,
            temp_f: 39.6,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 196,
            wind_dir: "SSW",
            pressure_mb: 1033,
            pressure_in: 30.52,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 80,
            cloud: 33,
            feelslike_c: 2.8,
            feelslike_f: 37,
            windchill_c: 2.8,
            windchill_f: 37,
            heatindex_c: 4.2,
            heatindex_f: 39.6,
            dewpoint_c: 1.1,
            dewpoint_f: 33.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.6,
            gust_kph: 10.7,
            uv: 1,
          },
          {
            time_epoch: 1706670000,
            time: "2024-01-31 03:00",
            temp_c: 4.1,
            temp_f: 39.4,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 199,
            wind_dir: "SSW",
            pressure_mb: 1033,
            pressure_in: 30.51,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 80,
            cloud: 12,
            feelslike_c: 2.6,
            feelslike_f: 36.6,
            windchill_c: 2.6,
            windchill_f: 36.6,
            heatindex_c: 4.1,
            heatindex_f: 39.4,
            dewpoint_c: 1,
            dewpoint_f: 33.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.1,
            gust_kph: 11.4,
            uv: 1,
          },
          {
            time_epoch: 1706673600,
            time: "2024-01-31 04:00",
            temp_c: 3.9,
            temp_f: 39.1,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 212,
            wind_dir: "SSW",
            pressure_mb: 1033,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 81,
            cloud: 3,
            feelslike_c: 2.6,
            feelslike_f: 36.6,
            windchill_c: 2.6,
            windchill_f: 36.6,
            heatindex_c: 3.9,
            heatindex_f: 39.1,
            dewpoint_c: 1,
            dewpoint_f: 33.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.4,
            gust_kph: 10.3,
            uv: 1,
          },
          {
            time_epoch: 1706677200,
            time: "2024-01-31 05:00",
            temp_c: 3.8,
            temp_f: 38.9,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 198,
            wind_dir: "SSW",
            pressure_mb: 1032,
            pressure_in: 30.47,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 84,
            cloud: 4,
            feelslike_c: 1.6,
            feelslike_f: 34.8,
            windchill_c: 1.6,
            windchill_f: 34.8,
            heatindex_c: 3.8,
            heatindex_f: 38.9,
            dewpoint_c: 1.3,
            dewpoint_f: 34.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.5,
            gust_kph: 15.3,
            uv: 1,
          },
          {
            time_epoch: 1706680800,
            time: "2024-01-31 06:00",
            temp_c: 3.7,
            temp_f: 38.7,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 217,
            wind_dir: "SW",
            pressure_mb: 1033,
            pressure_in: 30.49,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 88,
            cloud: 16,
            feelslike_c: 1.5,
            feelslike_f: 34.6,
            windchill_c: 1.5,
            windchill_f: 34.6,
            heatindex_c: 3.7,
            heatindex_f: 38.7,
            dewpoint_c: 1.9,
            dewpoint_f: 35.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.3,
            gust_kph: 15,
            uv: 1,
          },
          {
            time_epoch: 1706684400,
            time: "2024-01-31 07:00",
            temp_c: 3.6,
            temp_f: 38.5,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 211,
            wind_dir: "SSW",
            pressure_mb: 1032,
            pressure_in: 30.48,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 91,
            cloud: 26,
            feelslike_c: 1.4,
            feelslike_f: 34.6,
            windchill_c: 1.4,
            windchill_f: 34.6,
            heatindex_c: 3.6,
            heatindex_f: 38.5,
            dewpoint_c: 2.3,
            dewpoint_f: 36.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9,
            gust_kph: 14.5,
            uv: 1,
          },
          {
            time_epoch: 1706688000,
            time: "2024-01-31 08:00",
            temp_c: 3.7,
            temp_f: 38.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 214,
            wind_dir: "SW",
            pressure_mb: 1032,
            pressure_in: 30.48,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 91,
            cloud: 22,
            feelslike_c: 1.5,
            feelslike_f: 34.7,
            windchill_c: 1.5,
            windchill_f: 34.7,
            heatindex_c: 3.7,
            heatindex_f: 38.6,
            dewpoint_c: 2.3,
            dewpoint_f: 36.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9,
            gust_kph: 14.5,
            uv: 2,
          },
          {
            time_epoch: 1706691600,
            time: "2024-01-31 09:00",
            temp_c: 4.5,
            temp_f: 40,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 210,
            wind_dir: "SSW",
            pressure_mb: 1032,
            pressure_in: 30.47,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 87,
            cloud: 26,
            feelslike_c: 2,
            feelslike_f: 35.6,
            windchill_c: 2,
            windchill_f: 35.6,
            heatindex_c: 4.5,
            heatindex_f: 40,
            dewpoint_c: 2.5,
            dewpoint_f: 36.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.2,
            gust_kph: 16.3,
            uv: 2,
          },
          {
            time_epoch: 1706695200,
            time: "2024-01-31 10:00",
            temp_c: 5.7,
            temp_f: 42.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 219,
            wind_dir: "SW",
            pressure_mb: 1032,
            pressure_in: 30.47,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 81,
            cloud: 13,
            feelslike_c: 2.9,
            feelslike_f: 37.2,
            windchill_c: 2.9,
            windchill_f: 37.2,
            heatindex_c: 5.7,
            heatindex_f: 42.3,
            dewpoint_c: 2.7,
            dewpoint_f: 36.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.4,
            gust_kph: 19.9,
            uv: 3,
          },
          {
            time_epoch: 1706698800,
            time: "2024-01-31 11:00",
            temp_c: 6.9,
            temp_f: 44.5,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 217,
            wind_dir: "SW",
            pressure_mb: 1031,
            pressure_in: 30.45,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 74,
            cloud: 42,
            feelslike_c: 4,
            feelslike_f: 39.3,
            windchill_c: 4,
            windchill_f: 39.3,
            heatindex_c: 6.9,
            heatindex_f: 44.5,
            dewpoint_c: 2.6,
            dewpoint_f: 36.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.4,
            gust_kph: 21.6,
            uv: 3,
          },
          {
            time_epoch: 1706702400,
            time: "2024-01-31 12:00",
            temp_c: 7.8,
            temp_f: 46.1,
            is_day: 1,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 11.2,
            wind_kph: 18,
            wind_degree: 216,
            wind_dir: "SW",
            pressure_mb: 1030,
            pressure_in: 30.42,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 70,
            cloud: 100,
            feelslike_c: 4.9,
            feelslike_f: 40.7,
            windchill_c: 4.9,
            windchill_f: 40.7,
            heatindex_c: 7.8,
            heatindex_f: 46.1,
            dewpoint_c: 2.7,
            dewpoint_f: 36.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15,
            gust_kph: 24.1,
            uv: 2,
          },
          {
            time_epoch: 1706706000,
            time: "2024-01-31 13:00",
            temp_c: 8.5,
            temp_f: 47.2,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 11,
            wind_kph: 17.6,
            wind_degree: 223,
            wind_dir: "SW",
            pressure_mb: 1029,
            pressure_in: 30.39,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 71,
            cloud: 40,
            feelslike_c: 5.7,
            feelslike_f: 42.2,
            windchill_c: 5.7,
            windchill_f: 42.2,
            heatindex_c: 8.5,
            heatindex_f: 47.2,
            dewpoint_c: 3.5,
            dewpoint_f: 38.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.8,
            gust_kph: 23.8,
            uv: 3,
          },
          {
            time_epoch: 1706709600,
            time: "2024-01-31 14:00",
            temp_c: 9.2,
            temp_f: 48.5,
            is_day: 1,
            condition: {
              text: "Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 11.9,
            wind_kph: 19.1,
            wind_degree: 222,
            wind_dir: "SW",
            pressure_mb: 1028,
            pressure_in: 30.36,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 72,
            cloud: 78,
            feelslike_c: 6.5,
            feelslike_f: 43.6,
            windchill_c: 6.5,
            windchill_f: 43.6,
            heatindex_c: 9.2,
            heatindex_f: 48.5,
            dewpoint_c: 4.5,
            dewpoint_f: 40,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.9,
            gust_kph: 25.6,
            uv: 2,
          },
          {
            time_epoch: 1706713200,
            time: "2024-01-31 15:00",
            temp_c: 9.1,
            temp_f: 48.4,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 12.1,
            wind_kph: 19.4,
            wind_degree: 221,
            wind_dir: "SW",
            pressure_mb: 1027,
            pressure_in: 30.34,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 76,
            cloud: 42,
            feelslike_c: 6.3,
            feelslike_f: 43.4,
            windchill_c: 6.3,
            windchill_f: 43.4,
            heatindex_c: 9.1,
            heatindex_f: 48.4,
            dewpoint_c: 5.2,
            dewpoint_f: 41.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 17.6,
            gust_kph: 28.3,
            uv: 3,
          },
          {
            time_epoch: 1706716800,
            time: "2024-01-31 16:00",
            temp_c: 8.9,
            temp_f: 48,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 13,
            wind_kph: 20.9,
            wind_degree: 218,
            wind_dir: "SW",
            pressure_mb: 1027,
            pressure_in: 30.32,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 80,
            cloud: 26,
            feelslike_c: 5.9,
            feelslike_f: 42.6,
            windchill_c: 5.9,
            windchill_f: 42.6,
            heatindex_c: 8.9,
            heatindex_f: 48,
            dewpoint_c: 5.7,
            dewpoint_f: 42.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 19.7,
            gust_kph: 31.8,
            uv: 3,
          },
          {
            time_epoch: 1706720400,
            time: "2024-01-31 17:00",
            temp_c: 8.5,
            temp_f: 47.3,
            is_day: 0,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 13.4,
            wind_kph: 21.6,
            wind_degree: 229,
            wind_dir: "SW",
            pressure_mb: 1027,
            pressure_in: 30.33,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 85,
            cloud: 100,
            feelslike_c: 5.4,
            feelslike_f: 41.6,
            windchill_c: 5.4,
            windchill_f: 41.6,
            heatindex_c: 8.5,
            heatindex_f: 47.3,
            dewpoint_c: 6.2,
            dewpoint_f: 43.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 21.1,
            gust_kph: 33.9,
            uv: 1,
          },
          {
            time_epoch: 1706724000,
            time: "2024-01-31 18:00",
            temp_c: 8.9,
            temp_f: 48.1,
            is_day: 0,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 14.1,
            wind_kph: 22.7,
            wind_degree: 232,
            wind_dir: "SW",
            pressure_mb: 1027,
            pressure_in: 30.32,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 88,
            cloud: 100,
            feelslike_c: 5.8,
            feelslike_f: 42.4,
            windchill_c: 5.8,
            windchill_f: 42.4,
            heatindex_c: 8.9,
            heatindex_f: 48.1,
            dewpoint_c: 7.1,
            dewpoint_f: 44.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 21.5,
            gust_kph: 34.7,
            uv: 1,
          },
          {
            time_epoch: 1706727600,
            time: "2024-01-31 19:00",
            temp_c: 9.7,
            temp_f: 49.4,
            is_day: 0,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 13.9,
            wind_kph: 22.3,
            wind_degree: 230,
            wind_dir: "SW",
            pressure_mb: 1026,
            pressure_in: 30.3,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 87,
            cloud: 100,
            feelslike_c: 6.8,
            feelslike_f: 44.2,
            windchill_c: 6.8,
            windchill_f: 44.2,
            heatindex_c: 9.7,
            heatindex_f: 49.4,
            dewpoint_c: 7.6,
            dewpoint_f: 45.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 21.5,
            gust_kph: 34.6,
            uv: 1,
          },
          {
            time_epoch: 1706731200,
            time: "2024-01-31 20:00",
            temp_c: 9.9,
            temp_f: 49.8,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 13.9,
            wind_kph: 22.3,
            wind_degree: 233,
            wind_dir: "SW",
            pressure_mb: 1026,
            pressure_in: 30.29,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 87,
            cloud: 62,
            feelslike_c: 7,
            feelslike_f: 44.6,
            windchill_c: 7,
            windchill_f: 44.6,
            heatindex_c: 9.9,
            heatindex_f: 49.8,
            dewpoint_c: 7.9,
            dewpoint_f: 46.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 22.3,
            gust_kph: 36,
            uv: 1,
          },
          {
            time_epoch: 1706734800,
            time: "2024-01-31 21:00",
            temp_c: 10,
            temp_f: 50,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 13.9,
            wind_kph: 22.3,
            wind_degree: 235,
            wind_dir: "SW",
            pressure_mb: 1026,
            pressure_in: 30.29,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 87,
            cloud: 60,
            feelslike_c: 7.2,
            feelslike_f: 44.9,
            windchill_c: 7.2,
            windchill_f: 44.9,
            heatindex_c: 10,
            heatindex_f: 50,
            dewpoint_c: 7.9,
            dewpoint_f: 46.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 22.2,
            gust_kph: 35.7,
            uv: 1,
          },
          {
            time_epoch: 1706738400,
            time: "2024-01-31 22:00",
            temp_c: 10,
            temp_f: 50.1,
            is_day: 0,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 13.4,
            wind_kph: 21.6,
            wind_degree: 247,
            wind_dir: "WSW",
            pressure_mb: 1026,
            pressure_in: 30.3,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 85,
            cloud: 100,
            feelslike_c: 7.3,
            feelslike_f: 45.1,
            windchill_c: 7.3,
            windchill_f: 45.1,
            heatindex_c: 10,
            heatindex_f: 50.1,
            dewpoint_c: 7.6,
            dewpoint_f: 45.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 21.3,
            gust_kph: 34.2,
            uv: 1,
          },
          {
            time_epoch: 1706742000,
            time: "2024-01-31 23:00",
            temp_c: 10.1,
            temp_f: 50.2,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 12.5,
            wind_kph: 20.2,
            wind_degree: 251,
            wind_dir: "WSW",
            pressure_mb: 1026,
            pressure_in: 30.31,
            precip_mm: 0.01,
            precip_in: 0,
            snow_cm: 0,
            humidity: 82,
            cloud: 100,
            feelslike_c: 7.5,
            feelslike_f: 45.6,
            windchill_c: 7.5,
            windchill_f: 45.6,
            heatindex_c: 10.1,
            heatindex_f: 50.3,
            dewpoint_c: 7.3,
            dewpoint_f: 45.1,
            will_it_rain: 1,
            chance_of_rain: 82,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 19.3,
            gust_kph: 31,
            uv: 1,
          },
        ],
      },
      {
        date: "2024-02-01",
        date_epoch: 1706745600,
        day: {
          maxtemp_c: 9.2,
          maxtemp_f: 48.5,
          mintemp_c: 5.9,
          mintemp_f: 42.7,
          avgtemp_c: 7.9,
          avgtemp_f: 46.2,
          maxwind_mph: 11.9,
          maxwind_kph: 19.1,
          totalprecip_mm: 0.14,
          totalprecip_in: 0.01,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 69,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 88,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain nearby",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 1,
        },
        astro: {
          sunrise: "07:40 AM",
          sunset: "04:49 PM",
          moonrise: "No moonrise",
          moonset: "09:54 AM",
          moon_phase: "Waning Gibbous",
          moon_illumination: 69,
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1706745600,
            time: "2024-02-01 00:00",
            temp_c: 10.1,
            temp_f: 50.1,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 11.9,
            wind_kph: 19.1,
            wind_degree: 256,
            wind_dir: "WSW",
            pressure_mb: 1027,
            pressure_in: 30.32,
            precip_mm: 0.05,
            precip_in: 0,
            snow_cm: 0,
            humidity: 83,
            cloud: 100,
            feelslike_c: 7.6,
            feelslike_f: 45.6,
            windchill_c: 7.6,
            windchill_f: 45.6,
            heatindex_c: 10.1,
            heatindex_f: 50.1,
            dewpoint_c: 7.4,
            dewpoint_f: 45.4,
            will_it_rain: 0,
            chance_of_rain: 68,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 18.2,
            gust_kph: 29.3,
            uv: 1,
          },
          {
            time_epoch: 1706749200,
            time: "2024-02-01 01:00",
            temp_c: 9.8,
            temp_f: 49.7,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 260,
            wind_dir: "W",
            pressure_mb: 1027,
            pressure_in: 30.32,
            precip_mm: 0.05,
            precip_in: 0,
            snow_cm: 0,
            humidity: 89,
            cloud: 100,
            feelslike_c: 7.5,
            feelslike_f: 45.4,
            windchill_c: 7.5,
            windchill_f: 45.4,
            heatindex_c: 9.8,
            heatindex_f: 49.7,
            dewpoint_c: 8.1,
            dewpoint_f: 46.5,
            will_it_rain: 1,
            chance_of_rain: 85,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 16.5,
            gust_kph: 26.5,
            uv: 1,
          },
          {
            time_epoch: 1706752800,
            time: "2024-02-01 02:00",
            temp_c: 9.9,
            temp_f: 49.8,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 270,
            wind_dir: "W",
            pressure_mb: 1027,
            pressure_in: 30.34,
            precip_mm: 0.01,
            precip_in: 0,
            snow_cm: 0,
            humidity: 91,
            cloud: 100,
            feelslike_c: 7.6,
            feelslike_f: 45.7,
            windchill_c: 7.6,
            windchill_f: 45.7,
            heatindex_c: 9.9,
            heatindex_f: 49.8,
            dewpoint_c: 8.6,
            dewpoint_f: 47.4,
            will_it_rain: 1,
            chance_of_rain: 88,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.8,
            gust_kph: 25.5,
            uv: 1,
          },
          {
            time_epoch: 1706756400,
            time: "2024-02-01 03:00",
            temp_c: 9.6,
            temp_f: 49.4,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 311,
            wind_dir: "NW",
            pressure_mb: 1029,
            pressure_in: 30.38,
            precip_mm: 0.03,
            precip_in: 0,
            snow_cm: 0,
            humidity: 91,
            cloud: 100,
            feelslike_c: 7.3,
            feelslike_f: 45.2,
            windchill_c: 7.3,
            windchill_f: 45.2,
            heatindex_c: 9.7,
            heatindex_f: 49.4,
            dewpoint_c: 8.3,
            dewpoint_f: 46.9,
            will_it_rain: 0,
            chance_of_rain: 63,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.9,
            gust_kph: 24,
            uv: 1,
          },
          {
            time_epoch: 1706760000,
            time: "2024-02-01 04:00",
            temp_c: 8.7,
            temp_f: 47.6,
            is_day: 0,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 339,
            wind_dir: "NNW",
            pressure_mb: 1029,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 77,
            cloud: 100,
            feelslike_c: 6.7,
            feelslike_f: 44.1,
            windchill_c: 6.7,
            windchill_f: 44.1,
            heatindex_c: 8.7,
            heatindex_f: 47.6,
            dewpoint_c: 4.9,
            dewpoint_f: 40.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.3,
            gust_kph: 16.6,
            uv: 1,
          },
          {
            time_epoch: 1706763600,
            time: "2024-02-01 05:00",
            temp_c: 8.3,
            temp_f: 46.9,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 328,
            wind_dir: "NNW",
            pressure_mb: 1030,
            pressure_in: 30.43,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 73,
            cloud: 48,
            feelslike_c: 6.5,
            feelslike_f: 43.6,
            windchill_c: 6.5,
            windchill_f: 43.6,
            heatindex_c: 8.3,
            heatindex_f: 46.9,
            dewpoint_c: 3.7,
            dewpoint_f: 38.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.6,
            gust_kph: 15.4,
            uv: 1,
          },
          {
            time_epoch: 1706767200,
            time: "2024-02-01 06:00",
            temp_c: 7.8,
            temp_f: 46,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 345,
            wind_dir: "NNW",
            pressure_mb: 1031,
            pressure_in: 30.46,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 71,
            cloud: 5,
            feelslike_c: 5.7,
            feelslike_f: 42.3,
            windchill_c: 5.7,
            windchill_f: 42.3,
            heatindex_c: 7.8,
            heatindex_f: 46,
            dewpoint_c: 2.9,
            dewpoint_f: 37.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10,
            gust_kph: 16,
            uv: 1,
          },
          {
            time_epoch: 1706770800,
            time: "2024-02-01 07:00",
            temp_c: 6.6,
            temp_f: 43.9,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6,
            wind_kph: 9.7,
            wind_degree: 342,
            wind_dir: "NNW",
            pressure_mb: 1032,
            pressure_in: 30.48,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 70,
            cloud: 2,
            feelslike_c: 4.6,
            feelslike_f: 40.3,
            windchill_c: 4.6,
            windchill_f: 40.3,
            heatindex_c: 6.6,
            heatindex_f: 43.9,
            dewpoint_c: 1.5,
            dewpoint_f: 34.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.9,
            gust_kph: 14.3,
            uv: 1,
          },
          {
            time_epoch: 1706774400,
            time: "2024-02-01 08:00",
            temp_c: 5.9,
            temp_f: 42.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 339,
            wind_dir: "NNW",
            pressure_mb: 1033,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 70,
            cloud: 6,
            feelslike_c: 4.2,
            feelslike_f: 39.5,
            windchill_c: 4.2,
            windchill_f: 39.5,
            heatindex_c: 5.9,
            heatindex_f: 42.7,
            dewpoint_c: 0.9,
            dewpoint_f: 33.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.9,
            gust_kph: 12.7,
            uv: 3,
          },
          {
            time_epoch: 1706778000,
            time: "2024-02-01 09:00",
            temp_c: 6.3,
            temp_f: 43.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 331,
            wind_dir: "NNW",
            pressure_mb: 1034,
            pressure_in: 30.53,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 68,
            cloud: 11,
            feelslike_c: 4.6,
            feelslike_f: 40.4,
            windchill_c: 4.6,
            windchill_f: 40.4,
            heatindex_c: 6.3,
            heatindex_f: 43.3,
            dewpoint_c: 0.9,
            dewpoint_f: 33.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7,
            gust_kph: 11.3,
            uv: 3,
          },
          {
            time_epoch: 1706781600,
            time: "2024-02-01 10:00",
            temp_c: 7,
            temp_f: 44.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 330,
            wind_dir: "NNW",
            pressure_mb: 1035,
            pressure_in: 30.55,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 64,
            cloud: 9,
            feelslike_c: 5.3,
            feelslike_f: 41.6,
            windchill_c: 5.3,
            windchill_f: 41.6,
            heatindex_c: 7,
            heatindex_f: 44.6,
            dewpoint_c: 0.6,
            dewpoint_f: 33.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.1,
            gust_kph: 11.4,
            uv: 3,
          },
          {
            time_epoch: 1706785200,
            time: "2024-02-01 11:00",
            temp_c: 7.9,
            temp_f: 46.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 320,
            wind_dir: "NW",
            pressure_mb: 1035,
            pressure_in: 30.56,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 58,
            cloud: 9,
            feelslike_c: 6.5,
            feelslike_f: 43.7,
            windchill_c: 6.5,
            windchill_f: 43.7,
            heatindex_c: 7.9,
            heatindex_f: 46.2,
            dewpoint_c: 0.1,
            dewpoint_f: 32.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.2,
            gust_kph: 9.9,
            uv: 3,
          },
          {
            time_epoch: 1706788800,
            time: "2024-02-01 12:00",
            temp_c: 8.5,
            temp_f: 47.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 314,
            wind_dir: "NW",
            pressure_mb: 1035,
            pressure_in: 30.55,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 53,
            cloud: 14,
            feelslike_c: 7.5,
            feelslike_f: 45.6,
            windchill_c: 7.5,
            windchill_f: 45.6,
            heatindex_c: 8.5,
            heatindex_f: 47.3,
            dewpoint_c: -0.4,
            dewpoint_f: 31.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.2,
            gust_kph: 8.4,
            uv: 3,
          },
          {
            time_epoch: 1706792400,
            time: "2024-02-01 13:00",
            temp_c: 9,
            temp_f: 48.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 292,
            wind_dir: "WNW",
            pressure_mb: 1034,
            pressure_in: 30.54,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 50,
            cloud: 20,
            feelslike_c: 8.1,
            feelslike_f: 46.5,
            windchill_c: 8.1,
            windchill_f: 46.5,
            heatindex_c: 9,
            heatindex_f: 48.1,
            dewpoint_c: -0.8,
            dewpoint_f: 30.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.2,
            gust_kph: 8.4,
            uv: 3,
          },
          {
            time_epoch: 1706796000,
            time: "2024-02-01 14:00",
            temp_c: 9.2,
            temp_f: 48.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 275,
            wind_dir: "W",
            pressure_mb: 1034,
            pressure_in: 30.53,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 49,
            cloud: 24,
            feelslike_c: 8.1,
            feelslike_f: 46.5,
            windchill_c: 8.1,
            windchill_f: 46.5,
            heatindex_c: 9.2,
            heatindex_f: 48.5,
            dewpoint_c: -0.9,
            dewpoint_f: 30.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.2,
            gust_kph: 10,
            uv: 3,
          },
          {
            time_epoch: 1706799600,
            time: "2024-02-01 15:00",
            temp_c: 9,
            temp_f: 48.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 266,
            wind_dir: "W",
            pressure_mb: 1034,
            pressure_in: 30.52,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 51,
            cloud: 16,
            feelslike_c: 7.8,
            feelslike_f: 46.1,
            windchill_c: 7.8,
            windchill_f: 46.1,
            heatindex_c: 9,
            heatindex_f: 48.1,
            dewpoint_c: -0.7,
            dewpoint_f: 30.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.6,
            gust_kph: 10.5,
            uv: 3,
          },
          {
            time_epoch: 1706803200,
            time: "2024-02-01 16:00",
            temp_c: 8.5,
            temp_f: 47.3,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 255,
            wind_dir: "WSW",
            pressure_mb: 1034,
            pressure_in: 30.52,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 54,
            cloud: 27,
            feelslike_c: 7.4,
            feelslike_f: 45.4,
            windchill_c: 7.4,
            windchill_f: 45.4,
            heatindex_c: 8.5,
            heatindex_f: 47.3,
            dewpoint_c: -0.4,
            dewpoint_f: 31.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.4,
            gust_kph: 10.3,
            uv: 3,
          },
          {
            time_epoch: 1706806800,
            time: "2024-02-01 17:00",
            temp_c: 7.5,
            temp_f: 45.4,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 232,
            wind_dir: "SW",
            pressure_mb: 1033,
            pressure_in: 30.51,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 58,
            cloud: 13,
            feelslike_c: 6.3,
            feelslike_f: 43.4,
            windchill_c: 6.3,
            windchill_f: 43.4,
            heatindex_c: 7.5,
            heatindex_f: 45.4,
            dewpoint_c: -0.3,
            dewpoint_f: 31.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.9,
            gust_kph: 11.1,
            uv: 1,
          },
          {
            time_epoch: 1706810400,
            time: "2024-02-01 18:00",
            temp_c: 7.3,
            temp_f: 45.1,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 228,
            wind_dir: "SW",
            pressure_mb: 1033,
            pressure_in: 30.51,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 60,
            cloud: 11,
            feelslike_c: 6.2,
            feelslike_f: 43.1,
            windchill_c: 6.2,
            windchill_f: 43.1,
            heatindex_c: 7.3,
            heatindex_f: 45.1,
            dewpoint_c: 0.1,
            dewpoint_f: 32.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.6,
            gust_kph: 10.5,
            uv: 1,
          },
          {
            time_epoch: 1706814000,
            time: "2024-02-01 19:00",
            temp_c: 6.9,
            temp_f: 44.5,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 223,
            wind_dir: "SW",
            pressure_mb: 1033,
            pressure_in: 30.52,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 64,
            cloud: 47,
            feelslike_c: 5.5,
            feelslike_f: 42,
            windchill_c: 5.5,
            windchill_f: 42,
            heatindex_c: 6.9,
            heatindex_f: 44.5,
            dewpoint_c: 0.6,
            dewpoint_f: 33.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.7,
            gust_kph: 12.4,
            uv: 1,
          },
          {
            time_epoch: 1706817600,
            time: "2024-02-01 20:00",
            temp_c: 6.7,
            temp_f: 44,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 221,
            wind_dir: "SW",
            pressure_mb: 1033,
            pressure_in: 30.51,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 70,
            cloud: 18,
            feelslike_c: 4.5,
            feelslike_f: 40.1,
            windchill_c: 4.5,
            windchill_f: 40.1,
            heatindex_c: 6.7,
            heatindex_f: 44,
            dewpoint_c: 1.6,
            dewpoint_f: 34.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.8,
            gust_kph: 17.4,
            uv: 1,
          },
          {
            time_epoch: 1706821200,
            time: "2024-02-01 21:00",
            temp_c: 6.4,
            temp_f: 43.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 229,
            wind_dir: "SW",
            pressure_mb: 1033,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 77,
            cloud: 5,
            feelslike_c: 3.9,
            feelslike_f: 38.9,
            windchill_c: 3.9,
            windchill_f: 38.9,
            heatindex_c: 6.4,
            heatindex_f: 43.5,
            dewpoint_c: 2.7,
            dewpoint_f: 36.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.6,
            gust_kph: 20.3,
            uv: 1,
          },
          {
            time_epoch: 1706824800,
            time: "2024-02-01 22:00",
            temp_c: 6.3,
            temp_f: 43.4,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 238,
            wind_dir: "WSW",
            pressure_mb: 1033,
            pressure_in: 30.49,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 82,
            cloud: 3,
            feelslike_c: 3.5,
            feelslike_f: 38.3,
            windchill_c: 3.5,
            windchill_f: 38.3,
            heatindex_c: 6.3,
            heatindex_f: 43.4,
            dewpoint_c: 3.5,
            dewpoint_f: 38.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.4,
            gust_kph: 23.1,
            uv: 1,
          },
          {
            time_epoch: 1706828400,
            time: "2024-02-01 23:00",
            temp_c: 6.5,
            temp_f: 43.6,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 241,
            wind_dir: "WSW",
            pressure_mb: 1032,
            pressure_in: 30.48,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 86,
            cloud: 12,
            feelslike_c: 3.7,
            feelslike_f: 38.6,
            windchill_c: 3.7,
            windchill_f: 38.6,
            heatindex_c: 6.5,
            heatindex_f: 43.6,
            dewpoint_c: 4.3,
            dewpoint_f: 39.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.7,
            gust_kph: 23.7,
            uv: 1,
          },
        ],
      },
    ],
  },
};
